export const testimonials = [
    {
      id: 1,
      name: "Varun Kaushik",
      position: "CEO",
      company: "Opexn",
      image: "/varun.jpeg?height=80&width=80",
      rating: 4,
      text: "Galobyte transformed our digital presence beyond our wildest expectations. Their cosmic approach to technology solutions propelled our business into a new dimension of success. The team's expertise in AI and cloud solutions is truly stellar.",
      project: "Opexn",
    },
    {
      id: 2,
      name: "Ratan Mehta",
      position: "Co-Founder",
      company: "Think About",
      image: "/ratan.jpeg?height=80&width=80",
      rating: 4,
      text: "The CosmicLMS platform revolutionized our educational delivery. Students are more engaged, teachers love the interface, and our administrative efficiency has increased by 300%. Galobyte's attention to detail is phenomenal.",
      project: "Think About LMS",
    },
    {
      id: 3,
      name: "Anita Reddy",
      position: "Director of Digital Initiatives",
      company: "Medira Clinics",
      image: "/anita.jpeg?height=80&width=80",
      rating: 5,
      text: "We approached Galobyte to modernize our patient engagement portal. They delivered a responsive, HIPAA-compliant platform that reduced appointment no-shows by over 40%. The communication and delivery timelines were spot on.",
      project: "Medira Patient Portal",
    },
    // {
    //   id: 4,
    //   name: "Amit Grover",
    //   position: "Product Head",
    //   company: "FinNexa",
    //   image: "/amit.jpeg?height=80&width=80",
    //   rating: 5,
    //   text: "The dashboard and analytics platform Galobyte built for us gave our product a much-needed edge. Real-time reporting and streamlined user flows helped us onboard 3x more users within the first month post-launch.",
    //   project: "FinNexa Insights Dashboard",
    // },
    {
      id: 4,
      name: "Priya Narang",
      position: "COO",
      company: "Zocta Technologies",
      image: "/priya.jpeg?height=80&width=80",
      rating: 5,
      text: "We were scaling fast and needed a reliable team to revamp our internal tools. Galobyte not only built what we needed, but also suggested better architecture decisions. Their delivery was clean and ahead of schedule.",
      project: "Zocta Ops Suite",
    },
  ]
